Repository NicholasG04/Prom, pull requests merged in 2022-03, with the labels that each got.

#88 Ticket Implementation
  .env.local.example
  package.json
  pnpm-lock.yaml
  src/components/Checkout/CheckoutForm.tsx
  src/components/UserPanel/HasTicket.tsx
  src/components/UserPanel/NoTicket.tsx
  src/pages/admin/index.tsx
  src/pages/admin/scanner.tsx
  src/pages/api/getAllUsers.ts
  src/pages/api/getTicketlessUsers.ts
  src/pages/api/stripe/capture-intent.ts
  src/pages/api/stripe/connection-token.ts
  src/pages/api/stripe/webhook.ts
  src/pages/api/tickets/checkIn.ts
  src/pages/panel.tsx
  src/util/theme.ts
  src/util/ticketContext.tsx
Labels: enhancement, User Panel, Admin Panel

#89 refactor: start scanner/qr refactor
  package.json
  pnpm-lock.yaml
  src/components/Checkout/CheckoutForm.tsx
  src/components/Scanner/QRScanner.tsx
  src/components/UserPanel/HasTicket.tsx
  src/pages/admin/scanner.tsx
  src/pages/api/auth/[...supabase].ts
  src/pages/api/stripe/webhook.ts
  src/pages/api/tickets/checkIn.ts
  src/util/cookieOptions.ts
Labels: enhancement, UI, User Panel, Admin Panel

#97 feat: support tickets webhook
  .env.local.example
  package.json
  pnpm-lock.yaml
  src/pages/api/tickets/webhook.ts
Labels: enhancement

#98 Dev/Thanks section name update
  src/components/Layouts/Footer.tsx
Labels: enhancement, UI, High Priority

#93 one fucking word
  src/components/Home/Header.tsx
  src/components/Nav/NavBar.tsx
Labels: bug, UI, High Priority

#104 feat: add banner in support of ukraine
  src/components/Layouts/Banner.tsx
  src/components/Layouts/Base.tsx
  src/components/Layouts/Home.tsx
Labels: enhancement, UI

#105 Feat/toastonloginerror
  src/pages/index.tsx
Labels: bug, UI

#112 Admin Panel
  src/components/Admin/UserCard.tsx
  src/components/UserPanel/HasTicket.tsx
  src/components/UserPanel/QR.tsx
  src/pages/admin/[id]/index.tsx
  src/pages/admin/index.tsx
  src/pages/api/getAllUsersTicketInfo.ts
  src/pages/api/getUser/[id].ts
  src/types/user.ts
Labels: enhancement, UI, Admin Panel

#147 fix: sentry user data now augments correctly (#136)
  sentry.client.config.js
  sentry.server.config.js
  src/pages/_app.tsx
Labels: bug

#149 fix: Checking in ticket error #137
  src/pages/api/tickets/checkIn.ts
Labels: bug

#148 Feat/redonewording
  package.json
  pnpm-lock.yaml
  src/components/Home/Cards.tsx
  src/components/Home/Header.tsx
  src/components/Layouts/Footer.tsx
  src/pages/index.tsx
Labels: enhancement, UI

#152 fix: centre loading spinner on user panel (#145)
  src/pages/panel.tsx
Labels: bug, UI

#157 feat: colour of user card now changes based on ticket status (#135)
  src/components/Admin/UserCard.tsx
Labels: enhancement, UI, Admin Panel

#161 fix: can select users without a ticket now
  src/pages/admin/index.tsx
Labels: bug, UI, Admin Panel

#162 chore: update images
  public/favicon.ico
  public/icons/android-chrome-192x192.png
  public/icons/apple-touch-icon.png
  public/icons/icon-512x512.png
Labels: enhancement

#172 Update Pricing
  .env
  src/components/Home/Cards.tsx
  src/components/Terminal/TerminalStuff.tsx
  src/components/UserPanel/NoTicket.tsx
  src/pages/api/auth/[...supabase].ts
  src/pages/api/getAllUsersTicketInfo.ts
  src/pages/api/getTicketlessUsers.ts
  src/pages/api/getUser/[id].ts
  src/pages/api/stripe/capture-intent.ts
  src/pages/api/stripe/connection-token.ts
  src/pages/api/stripe/create-paymentintent.ts
  src/pages/api/stripe/webhook.ts
  src/pages/api/tickets/checkIn.ts
  src/pages/api/tickets/webhook.ts
Labels: enhancement, UI

#177 feat: add showing the user buying ticket for on terminal display
  src/components/Terminal/TerminalStuff.tsx
Labels: enhancement, Payments

#209 Implementation of uncheck in button
  src/pages/admin/[id]/index.tsx
Labels: enhancement, Admin Panel
