Repository NicholasG04/Prom, pull requests merged in 2022-02, with the labels that each got.

#9 Implement Chakra UI (#1)
  package.json
  pnpm-lock.yaml
  public/KimberleyBg.png
  public/kimberley_logo.png
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: enhancement, UI

#12 Implement Authentication with Next-Auth
  .env.local.example
  .eslintrc.js
  .gitignore
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/index.tsx
  src/util/theme.ts
Labels: enhancement, Authentication

#23 Implement Supabase
  .env.local.example
  .eslintrc.js
  .gitignore
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
  src/pages/index.tsx
  src/util/supabaseClient.ts
  src/util/useUser.tsx
Labels: enhancement, Authentication

#27 Create PWA and SEO
  .gitignore
  next.config.js
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  public/icons/android-chrome-192x192.png
  public/icons/apple-touch-icon.png
  public/icons/icon-512x512.png
  public/manifest.json
  src/pages/_app.tsx
Labels: enhancement

#30 made privacy and terms files and footer links
  package.json
  pnpm-lock.yaml
  src/components/Checkout/CheckoutForm.tsx
  src/components/Layouts/Footer.tsx
  src/pages/privacy.tsx
  src/pages/terms.tsx
Labels: enhancement

#55 feat: add lint ci
  .github/workflows/lint.yml
  package.json
Labels: enhancement

#41 Refactor: move to outsourced supabase stuff
  .env
  .env.development
  package.json
  pnpm-lock.yaml
  src/components/Checkout/CheckoutForm.tsx
  src/components/Checkout/CheckoutWrapper.tsx
  src/components/Home/Header.tsx
  src/components/Nav/NavBar.tsx
  src/pages/_app.tsx
  src/pages/api/auth.ts
  src/pages/api/auth/[...supabase].ts
  src/pages/api/getUser.ts
  src/pages/api/stripe/create-paymentintent.ts
  src/pages/checkout.tsx
  src/util/authHelpers.ts
  src/util/supabaseClient.ts
  src/util/theme.ts
  src/util/useUser.tsx
Labels: bug, enhancement, Authentication

#57 feat(analytics): add happykit analytics
  .env.local.example
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
Labels: enhancement

#37 Implements User Panel
  .eslintrc.js
  src/components/Checkout/CheckoutForm.tsx
  src/components/Checkout/CheckoutWrapper.tsx
  src/components/Home/Cards.tsx
  src/components/Home/Header.tsx
  src/components/Layouts/Base.tsx
  src/components/UserPanel/HasTicket.tsx
  src/components/UserPanel/MoreInfo.tsx
  src/components/UserPanel/NoTicket.tsx
  src/pages/_app.tsx
  src/pages/checkout.tsx
  src/pages/panel.tsx
  src/util/ticketContext.tsx
Labels: enhancement, User Panel

#72 Add Sentry
  .env.local.example
  .eslintrc.js
  .github/workflows/lint.yml
  .gitignore
  next.config.js
  package.json
  pnpm-lock.yaml
  sentry.client.config.js
  sentry.properties
  sentry.server.config.js
  src/pages/_app.tsx
  src/pages/_error.tsx
  src/pages/api/auth/[...supabase].ts
  src/pages/api/stripe/create-paymentintent.ts
  src/pages/api/stripe/webhook.ts
Labels: enhancement

#65 Stripe Terminal
  .env.local.example
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  src/components/Checkout/CheckoutForm.tsx
  src/components/Checkout/CheckoutWrapper.tsx
  src/components/Layouts/Base.tsx
  src/components/Nav/NavBar.tsx
  src/components/Nav/SignedInMenu.tsx
  src/components/Terminal/TerminalStuff.tsx
  src/components/Terminal/UserSelect.tsx
  src/pages/admin/[id]/index.tsx
  src/pages/admin/_middleware.ts
  src/pages/admin/index.tsx
  src/pages/admin/scanner.tsx
  src/pages/admin/terminal.tsx
  src/pages/api/getAllUsers.ts
  src/pages/api/getTicketlessUsers.ts
  src/pages/api/getUser/[id].ts
  src/pages/api/stripe/capture-intent.ts
  src/pages/api/stripe/connection-token.ts
  src/pages/api/stripe/create-paymentintent.ts
  src/pages/api/stripe/webhook.ts
  src/util/getStripe.ts
  src/util/stripeHelpers.ts
Labels: enhancement, help wanted, Admin Panel, Payments
